/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentmodelBody
 */
export interface ContentmodelBody {
    /**
     * 
     * @type {string}
     * @memberof ContentmodelBody
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ContentmodelBody
     */
    userId: number;
}

/**
 * Check if a given object implements the ContentmodelBody interface.
 */
export function instanceOfContentmodelBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ContentmodelBodyFromJSON(json: any): ContentmodelBody {
    return ContentmodelBodyFromJSONTyped(json, false);
}

export function ContentmodelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentmodelBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function ContentmodelBodyToJSON(value?: ContentmodelBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'userId': value.userId,
    };
}

