/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FieldtypeFieldType } from './FieldtypeFieldType';
import {
    FieldtypeFieldTypeFromJSON,
    FieldtypeFieldTypeFromJSONTyped,
    FieldtypeFieldTypeToJSON,
} from './FieldtypeFieldType';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
} from './GormDeletedAt';

/**
 * 
 * @export
 * @interface ContentmodelContentModel
 */
export interface ContentmodelContentModel {
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ContentmodelContentModel
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {Array<FieldtypeFieldType>}
     * @memberof ContentmodelContentModel
     */
    fieldTypes?: Array<FieldtypeFieldType>;
    /**
     * 
     * @type {number}
     * @memberof ContentmodelContentModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ContentmodelContentModel
     */
    userId: number;
}

/**
 * Check if a given object implements the ContentmodelContentModel interface.
 */
export function instanceOfContentmodelContentModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ContentmodelContentModelFromJSON(json: any): ContentmodelContentModel {
    return ContentmodelContentModelFromJSONTyped(json, false);
}

export function ContentmodelContentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentmodelContentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : GormDeletedAtFromJSON(json['deletedAt']),
        'fieldTypes': !exists(json, 'fieldTypes') ? undefined : ((json['fieldTypes'] as Array<any>).map(FieldtypeFieldTypeFromJSON)),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'userId': json['userId'],
    };
}

export function ContentmodelContentModelToJSON(value?: ContentmodelContentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'deletedAt': GormDeletedAtToJSON(value.deletedAt),
        'fieldTypes': value.fieldTypes === undefined ? undefined : ((value.fieldTypes as Array<any>).map(FieldtypeFieldTypeToJSON)),
        'id': value.id,
        'name': value.name,
        'updatedAt': value.updatedAt,
        'userId': value.userId,
    };
}

