/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentBody
 */
export interface ContentBody {
    /**
     * 
     * @type {number}
     * @memberof ContentBody
     */
    modelId: number;
    /**
     * 
     * @type {string}
     * @memberof ContentBody
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ContentBody
     */
    userId: number;
}

/**
 * Check if a given object implements the ContentBody interface.
 */
export function instanceOfContentBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modelId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ContentBodyFromJSON(json: any): ContentBody {
    return ContentBodyFromJSONTyped(json, false);
}

export function ContentBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modelId': json['modelId'],
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function ContentBodyToJSON(value?: ContentBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modelId': value.modelId,
        'name': value.name,
        'userId': value.userId,
    };
}

