/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldtypeBody
 */
export interface FieldtypeBody {
    /**
     * 
     * @type {number}
     * @memberof FieldtypeBody
     */
    contentModelId: number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeBody
     */
    fieldType?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeBody
     */
    name: string;
}

/**
 * Check if a given object implements the FieldtypeBody interface.
 */
export function instanceOfFieldtypeBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentModelId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FieldtypeBodyFromJSON(json: any): FieldtypeBody {
    return FieldtypeBodyFromJSONTyped(json, false);
}

export function FieldtypeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldtypeBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentModelId': json['contentModelId'],
        'fieldType': !exists(json, 'fieldType') ? undefined : json['fieldType'],
        'name': json['name'],
    };
}

export function FieldtypeBodyToJSON(value?: FieldtypeBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentModelId': value.contentModelId,
        'fieldType': value.fieldType,
        'name': value.name,
    };
}

