/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
} from './GormDeletedAt';

/**
 * 
 * @export
 * @interface FieldtypeFieldType
 */
export interface FieldtypeFieldType {
    /**
     * 
     * @type {number}
     * @memberof FieldtypeFieldType
     */
    contentModelId: number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof FieldtypeFieldType
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    fieldType?: string;
    /**
     * 
     * @type {number}
     * @memberof FieldtypeFieldType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the FieldtypeFieldType interface.
 */
export function instanceOfFieldtypeFieldType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentModelId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FieldtypeFieldTypeFromJSON(json: any): FieldtypeFieldType {
    return FieldtypeFieldTypeFromJSONTyped(json, false);
}

export function FieldtypeFieldTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldtypeFieldType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentModelId': json['contentModelId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : GormDeletedAtFromJSON(json['deletedAt']),
        'fieldType': !exists(json, 'fieldType') ? undefined : json['fieldType'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function FieldtypeFieldTypeToJSON(value?: FieldtypeFieldType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentModelId': value.contentModelId,
        'createdAt': value.createdAt,
        'deletedAt': GormDeletedAtToJSON(value.deletedAt),
        'fieldType': value.fieldType,
        'id': value.id,
        'name': value.name,
        'updatedAt': value.updatedAt,
    };
}

