/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldBody
 */
export interface FieldBody {
    /**
     * 
     * @type {number}
     * @memberof FieldBody
     */
    contentId: number;
    /**
     * 
     * @type {string}
     * @memberof FieldBody
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FieldBody
     */
    typeId: number;
    /**
     * 
     * @type {string}
     * @memberof FieldBody
     */
    value?: string;
}

/**
 * Check if a given object implements the FieldBody interface.
 */
export function instanceOfFieldBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contentId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "typeId" in value;

    return isInstance;
}

export function FieldBodyFromJSON(json: any): FieldBody {
    return FieldBodyFromJSONTyped(json, false);
}

export function FieldBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentId': json['contentId'],
        'name': json['name'],
        'typeId': json['typeId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function FieldBodyToJSON(value?: FieldBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentId': value.contentId,
        'name': value.name,
        'typeId': value.typeId,
        'value': value.value,
    };
}

