/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GormDeletedAt
 */
export interface GormDeletedAt {
    /**
     * 
     * @type {string}
     * @memberof GormDeletedAt
     */
    time?: string;
    /**
     * Valid is true if Time is not NULL
     * @type {boolean}
     * @memberof GormDeletedAt
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the GormDeletedAt interface.
 */
export function instanceOfGormDeletedAt(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GormDeletedAtFromJSON(json: any): GormDeletedAt {
    return GormDeletedAtFromJSONTyped(json, false);
}

export function GormDeletedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): GormDeletedAt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': !exists(json, 'time') ? undefined : json['time'],
        'valid': !exists(json, 'valid') ? undefined : json['valid'],
    };
}

export function GormDeletedAtToJSON(value?: GormDeletedAt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
        'valid': value.valid,
    };
}

