version: "3"

tasks:
  build:
    cmds:
      - swag init --parseDependency --parseInternal -g ./routes/index.go && go build .
  start:
    deps: [build]
    cmds:
      - go run .
  dev:
    deps: [build]
    cmds:
      - air
