/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ContentBody
 */
export interface ContentBody {
    /**
     * 
     * @type {number}
     * @memberof ContentBody
     */
    'modelId': number;
    /**
     * 
     * @type {string}
     * @memberof ContentBody
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ContentBody
     */
    'userId': string;
}
/**
 * 
 * @export
 * @interface ContentContent
 */
export interface ContentContent {
    /**
     * 
     * @type {ContentmodelContentModel}
     * @memberof ContentContent
     */
    'contentModel': ContentmodelContentModel;
    /**
     * 
     * @type {string}
     * @memberof ContentContent
     */
    'createdAt'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ContentContent
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ContentContent
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ContentContent
     */
    'modelId': number;
    /**
     * 
     * @type {string}
     * @memberof ContentContent
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ContentContent
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentContent
     */
    'userId': string;
}
/**
 * 
 * @export
 * @interface ContentmodelBody
 */
export interface ContentmodelBody {
    /**
     * 
     * @type {string}
     * @memberof ContentmodelBody
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelBody
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelBody
     */
    'userId': string;
}
/**
 * 
 * @export
 * @interface ContentmodelContentModel
 */
export interface ContentmodelContentModel {
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    'createdAt'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ContentmodelContentModel
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    'description'?: string;
    /**
     * 
     * @type {Array<FieldtypeFieldType>}
     * @memberof ContentmodelContentModel
     */
    'fieldTypes': Array<FieldtypeFieldType>;
    /**
     * 
     * @type {number}
     * @memberof ContentmodelContentModel
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentmodelContentModel
     */
    'userId': string;
}
/**
 * 
 * @export
 * @interface FieldBody
 */
export interface FieldBody {
    /**
     * 
     * @type {number}
     * @memberof FieldBody
     */
    'contentId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldBody
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof FieldBody
     */
    'typeId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldBody
     */
    'value'?: string;
}
/**
 * 
 * @export
 * @interface FieldField
 */
export interface FieldField {
    /**
     * 
     * @type {number}
     * @memberof FieldField
     */
    'contentId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldField
     */
    'createdAt'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof FieldField
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {FieldtypeFieldType}
     * @memberof FieldField
     */
    'fieldType': FieldtypeFieldType;
    /**
     * 
     * @type {number}
     * @memberof FieldField
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof FieldField
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof FieldField
     */
    'typeId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldField
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldField
     */
    'value'?: string;
}
/**
 * 
 * @export
 * @interface FieldtypeBody
 */
export interface FieldtypeBody {
    /**
     * 
     * @type {number}
     * @memberof FieldtypeBody
     */
    'contentModelId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeBody
     */
    'fieldType'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeBody
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface FieldtypeFieldType
 */
export interface FieldtypeFieldType {
    /**
     * 
     * @type {number}
     * @memberof FieldtypeFieldType
     */
    'contentModelId': number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    'createdAt'?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof FieldtypeFieldType
     */
    'deletedAt'?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    'fieldType'?: string;
    /**
     * 
     * @type {number}
     * @memberof FieldtypeFieldType
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FieldtypeFieldType
     */
    'updatedAt'?: string;
}
/**
 * 
 * @export
 * @interface GormDeletedAt
 */
export interface GormDeletedAt {
    /**
     * 
     * @type {string}
     * @memberof GormDeletedAt
     */
    'time'?: string;
    /**
     * Valid is true if Time is not NULL
     * @type {boolean}
     * @memberof GormDeletedAt
     */
    'valid'?: boolean;
}
/**
 * 
 * @export
 * @interface ModelsPagination
 */
export interface ModelsPagination {
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'offSet': number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPagination
     */
    'total': number;
}
/**
 * 
 * @export
 * @interface ModelsPaginationModelArrayContentContent
 */
export interface ModelsPaginationModelArrayContentContent {
    /**
     * 
     * @type {Array<ContentContent>}
     * @memberof ModelsPaginationModelArrayContentContent
     */
    'data': Array<ContentContent>;
    /**
     * 
     * @type {ModelsPagination}
     * @memberof ModelsPaginationModelArrayContentContent
     */
    'pagination': ModelsPagination;
}
/**
 * 
 * @export
 * @interface ModelsPaginationModelArrayContentmodelContentModel
 */
export interface ModelsPaginationModelArrayContentmodelContentModel {
    /**
     * 
     * @type {Array<ContentmodelContentModel>}
     * @memberof ModelsPaginationModelArrayContentmodelContentModel
     */
    'data': Array<ContentmodelContentModel>;
    /**
     * 
     * @type {ModelsPagination}
     * @memberof ModelsPaginationModelArrayContentmodelContentModel
     */
    'pagination': ModelsPagination;
}
/**
 * 
 * @export
 * @interface ModelsPaginationModelArrayFieldField
 */
export interface ModelsPaginationModelArrayFieldField {
    /**
     * 
     * @type {Array<FieldField>}
     * @memberof ModelsPaginationModelArrayFieldField
     */
    'data': Array<FieldField>;
    /**
     * 
     * @type {ModelsPagination}
     * @memberof ModelsPaginationModelArrayFieldField
     */
    'pagination': ModelsPagination;
}
/**
 * 
 * @export
 * @interface ModelsPaginationModelArrayFieldtypeFieldType
 */
export interface ModelsPaginationModelArrayFieldtypeFieldType {
    /**
     * 
     * @type {Array<FieldtypeFieldType>}
     * @memberof ModelsPaginationModelArrayFieldtypeFieldType
     */
    'data': Array<FieldtypeFieldType>;
    /**
     * 
     * @type {ModelsPagination}
     * @memberof ModelsPaginationModelArrayFieldtypeFieldType
     */
    'pagination': ModelsPagination;
}

/**
 * ContentApi - axios parameter creator
 * @export
 */
export const ContentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all content
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentGet: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/content`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete content
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentIdDelete', 'id', id)
            const localVarPath = `/v1/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get content by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentIdGet', 'id', id)
            const localVarPath = `/v1/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update content
         * @param {number} id ID
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdPut: async (id: number, request: ContentBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentIdPut', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1ContentIdPut', 'request', request)
            const localVarPath = `/v1/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create content
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentPost: async (request: ContentBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1ContentPost', 'request', request)
            const localVarPath = `/v1/content`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContentApi - functional programming interface
 * @export
 */
export const ContentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all content
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentGet(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsPaginationModelArrayContentContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentGet(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete content
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get content by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update content
         * @param {number} id ID
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentIdPut(id: number, request: ContentBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentIdPut(id, request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create content
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentPost(request: ContentBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentContent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentPost(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ContentApi - factory interface
 * @export
 */
export const ContentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContentApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all content
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentGet(page?: number, limit?: number, options?: any): AxiosPromise<ModelsPaginationModelArrayContentContent> {
            return localVarFp.v1ContentGet(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete content
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdDelete(id: number, options?: any): AxiosPromise<string> {
            return localVarFp.v1ContentIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get content by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdGet(id: number, options?: any): AxiosPromise<ContentContent> {
            return localVarFp.v1ContentIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update content
         * @param {number} id ID
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentIdPut(id: number, request: ContentBody, options?: any): AxiosPromise<ContentContent> {
            return localVarFp.v1ContentIdPut(id, request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create content
         * @param {ContentBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentPost(request: ContentBody, options?: any): AxiosPromise<ContentContent> {
            return localVarFp.v1ContentPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContentApi - object-oriented interface
 * @export
 * @class ContentApi
 * @extends {BaseAPI}
 */
export class ContentApi extends BaseAPI {
    /**
     * 
     * @summary Get all content
     * @param {number} [page] page
     * @param {number} [limit] limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public v1ContentGet(page?: number, limit?: number, options?: AxiosRequestConfig) {
        return ContentApiFp(this.configuration).v1ContentGet(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete content
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public v1ContentIdDelete(id: number, options?: AxiosRequestConfig) {
        return ContentApiFp(this.configuration).v1ContentIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get content by id
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public v1ContentIdGet(id: number, options?: AxiosRequestConfig) {
        return ContentApiFp(this.configuration).v1ContentIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update content
     * @param {number} id ID
     * @param {ContentBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public v1ContentIdPut(id: number, request: ContentBody, options?: AxiosRequestConfig) {
        return ContentApiFp(this.configuration).v1ContentIdPut(id, request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create content
     * @param {ContentBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public v1ContentPost(request: ContentBody, options?: AxiosRequestConfig) {
        return ContentApiFp(this.configuration).v1ContentPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ContentModelApi - axios parameter creator
 * @export
 */
export const ContentModelApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all content models
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelGet: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/contentModel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete content model
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentModelIdDelete', 'id', id)
            const localVarPath = `/v1/contentModel/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get content model by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentModelIdGet', 'id', id)
            const localVarPath = `/v1/contentModel/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update content model
         * @param {number} id ID
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdPut: async (id: number, request: ContentmodelBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1ContentModelIdPut', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1ContentModelIdPut', 'request', request)
            const localVarPath = `/v1/contentModel/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create content model
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelPost: async (request: ContentmodelBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1ContentModelPost', 'request', request)
            const localVarPath = `/v1/contentModel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContentModelApi - functional programming interface
 * @export
 */
export const ContentModelApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContentModelApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all content models
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentModelGet(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsPaginationModelArrayContentmodelContentModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentModelGet(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete content model
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentModelIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentModelIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get content model by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentModelIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentmodelContentModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentModelIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update content model
         * @param {number} id ID
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentModelIdPut(id: number, request: ContentmodelBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentmodelContentModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentModelIdPut(id, request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create content model
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ContentModelPost(request: ContentmodelBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentmodelContentModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ContentModelPost(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ContentModelApi - factory interface
 * @export
 */
export const ContentModelApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContentModelApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all content models
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelGet(page?: number, limit?: number, options?: any): AxiosPromise<ModelsPaginationModelArrayContentmodelContentModel> {
            return localVarFp.v1ContentModelGet(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete content model
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdDelete(id: number, options?: any): AxiosPromise<string> {
            return localVarFp.v1ContentModelIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get content model by id
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdGet(id: number, options?: any): AxiosPromise<ContentmodelContentModel> {
            return localVarFp.v1ContentModelIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update content model
         * @param {number} id ID
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelIdPut(id: number, request: ContentmodelBody, options?: any): AxiosPromise<ContentmodelContentModel> {
            return localVarFp.v1ContentModelIdPut(id, request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create content model
         * @param {ContentmodelBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ContentModelPost(request: ContentmodelBody, options?: any): AxiosPromise<ContentmodelContentModel> {
            return localVarFp.v1ContentModelPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContentModelApi - object-oriented interface
 * @export
 * @class ContentModelApi
 * @extends {BaseAPI}
 */
export class ContentModelApi extends BaseAPI {
    /**
     * 
     * @summary Get all content models
     * @param {number} [page] page
     * @param {number} [limit] limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentModelApi
     */
    public v1ContentModelGet(page?: number, limit?: number, options?: AxiosRequestConfig) {
        return ContentModelApiFp(this.configuration).v1ContentModelGet(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete content model
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentModelApi
     */
    public v1ContentModelIdDelete(id: number, options?: AxiosRequestConfig) {
        return ContentModelApiFp(this.configuration).v1ContentModelIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get content model by id
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentModelApi
     */
    public v1ContentModelIdGet(id: number, options?: AxiosRequestConfig) {
        return ContentModelApiFp(this.configuration).v1ContentModelIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update content model
     * @param {number} id ID
     * @param {ContentmodelBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentModelApi
     */
    public v1ContentModelIdPut(id: number, request: ContentmodelBody, options?: AxiosRequestConfig) {
        return ContentModelApiFp(this.configuration).v1ContentModelIdPut(id, request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create content model
     * @param {ContentmodelBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentModelApi
     */
    public v1ContentModelPost(request: ContentmodelBody, options?: AxiosRequestConfig) {
        return ContentModelApiFp(this.configuration).v1ContentModelPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * FieldApi - axios parameter creator
 * @export
 */
export const FieldApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all fields
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldGet: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/field`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete field
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1FieldIdDelete', 'id', id)
            const localVarPath = `/v1/field/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update field
         * @param {number} id ID
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldIdPut: async (id: number, request: FieldBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1FieldIdPut', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1FieldIdPut', 'request', request)
            const localVarPath = `/v1/field/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create field
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldPost: async (request: FieldBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1FieldPost', 'request', request)
            const localVarPath = `/v1/field`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FieldApi - functional programming interface
 * @export
 */
export const FieldApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FieldApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all fields
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldGet(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsPaginationModelArrayFieldField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldGet(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete field
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update field
         * @param {number} id ID
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldIdPut(id: number, request: FieldBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FieldField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldIdPut(id, request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create field
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldPost(request: FieldBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldPost(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FieldApi - factory interface
 * @export
 */
export const FieldApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FieldApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all fields
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldGet(page?: number, limit?: number, options?: any): AxiosPromise<ModelsPaginationModelArrayFieldField> {
            return localVarFp.v1FieldGet(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete field
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldIdDelete(id: number, options?: any): AxiosPromise<string> {
            return localVarFp.v1FieldIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update field
         * @param {number} id ID
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldIdPut(id: number, request: FieldBody, options?: any): AxiosPromise<FieldField> {
            return localVarFp.v1FieldIdPut(id, request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create field
         * @param {FieldBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldPost(request: FieldBody, options?: any): AxiosPromise<string> {
            return localVarFp.v1FieldPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FieldApi - object-oriented interface
 * @export
 * @class FieldApi
 * @extends {BaseAPI}
 */
export class FieldApi extends BaseAPI {
    /**
     * 
     * @summary Get all fields
     * @param {number} [page] page
     * @param {number} [limit] limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldApi
     */
    public v1FieldGet(page?: number, limit?: number, options?: AxiosRequestConfig) {
        return FieldApiFp(this.configuration).v1FieldGet(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete field
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldApi
     */
    public v1FieldIdDelete(id: number, options?: AxiosRequestConfig) {
        return FieldApiFp(this.configuration).v1FieldIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update field
     * @param {number} id ID
     * @param {FieldBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldApi
     */
    public v1FieldIdPut(id: number, request: FieldBody, options?: AxiosRequestConfig) {
        return FieldApiFp(this.configuration).v1FieldIdPut(id, request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create field
     * @param {FieldBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldApi
     */
    public v1FieldPost(request: FieldBody, options?: AxiosRequestConfig) {
        return FieldApiFp(this.configuration).v1FieldPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * FieldTypeApi - axios parameter creator
 * @export
 */
export const FieldTypeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all field types
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeGet: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/fieldType`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete field type
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1FieldTypeIdDelete', 'id', id)
            const localVarPath = `/v1/fieldType/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update field type
         * @param {number} id ID
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeIdPut: async (id: number, request: FieldtypeBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v1FieldTypeIdPut', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1FieldTypeIdPut', 'request', request)
            const localVarPath = `/v1/fieldType/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create field type
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypePost: async (request: FieldtypeBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('v1FieldTypePost', 'request', request)
            const localVarPath = `/v1/fieldType`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FieldTypeApi - functional programming interface
 * @export
 */
export const FieldTypeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FieldTypeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all field types
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldTypeGet(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsPaginationModelArrayFieldtypeFieldType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldTypeGet(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete field type
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldTypeIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldTypeIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update field type
         * @param {number} id ID
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldTypeIdPut(id: number, request: FieldtypeBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FieldtypeFieldType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldTypeIdPut(id, request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create field type
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1FieldTypePost(request: FieldtypeBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FieldtypeFieldType>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1FieldTypePost(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FieldTypeApi - factory interface
 * @export
 */
export const FieldTypeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FieldTypeApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all field types
         * @param {number} [page] page
         * @param {number} [limit] limit
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeGet(page?: number, limit?: number, options?: any): AxiosPromise<ModelsPaginationModelArrayFieldtypeFieldType> {
            return localVarFp.v1FieldTypeGet(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete field type
         * @param {number} id ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeIdDelete(id: number, options?: any): AxiosPromise<string> {
            return localVarFp.v1FieldTypeIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update field type
         * @param {number} id ID
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypeIdPut(id: number, request: FieldtypeBody, options?: any): AxiosPromise<FieldtypeFieldType> {
            return localVarFp.v1FieldTypeIdPut(id, request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create field type
         * @param {FieldtypeBody} request query params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1FieldTypePost(request: FieldtypeBody, options?: any): AxiosPromise<FieldtypeFieldType> {
            return localVarFp.v1FieldTypePost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FieldTypeApi - object-oriented interface
 * @export
 * @class FieldTypeApi
 * @extends {BaseAPI}
 */
export class FieldTypeApi extends BaseAPI {
    /**
     * 
     * @summary Get all field types
     * @param {number} [page] page
     * @param {number} [limit] limit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldTypeApi
     */
    public v1FieldTypeGet(page?: number, limit?: number, options?: AxiosRequestConfig) {
        return FieldTypeApiFp(this.configuration).v1FieldTypeGet(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete field type
     * @param {number} id ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldTypeApi
     */
    public v1FieldTypeIdDelete(id: number, options?: AxiosRequestConfig) {
        return FieldTypeApiFp(this.configuration).v1FieldTypeIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update field type
     * @param {number} id ID
     * @param {FieldtypeBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldTypeApi
     */
    public v1FieldTypeIdPut(id: number, request: FieldtypeBody, options?: AxiosRequestConfig) {
        return FieldTypeApiFp(this.configuration).v1FieldTypeIdPut(id, request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create field type
     * @param {FieldtypeBody} request query params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FieldTypeApi
     */
    public v1FieldTypePost(request: FieldtypeBody, options?: AxiosRequestConfig) {
        return FieldTypeApiFp(this.configuration).v1FieldTypePost(request, options).then((request) => request(this.axios, this.basePath));
    }
}


